spring:
  application:
    name: EurekaServer
server:
      port: 5000
  
eureka:
  client:
    service-url:
     defaultZone: http://localhost:5000/eureka/
          
   
    fetch-registry: false
    register-with-eureka: false  
   
 